services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-server
    expose:
      - 9000
